### ISSUE TITLE
lot / batch number missing from DgCertificate.cs

### ISSUE THREAD

**Issue by pappleby64** [ehn-dcc-development/hcert-dotnet#5]
DG Certificate class missing member for JSON element lot: (Bath Number)

**Comment by gunnarif** [comment]
Hi!
I don't see it in the schema DGC schema.
It's in the interoperability guideline but I don't think it has been specified in the DGC schema.

**Comment by pappleby64** [comment]
OK - I noticed it was missing when curiosity about the data and encoding of my own barcode status led me here. I've not looked at the spec (and have no need to)
