### ISSUE TITLE
Problem verifying signature

### ISSUE THREAD

**Issue by kansasdev** [ehn-dcc-development/hcert-dotnet#6]
Hello. Thanks for sharing project made in .net, it would help us a lot during our implementation.
I have been testing your code for verifying signature of COSE message and despite declaration in unit test that expected result (expectedverify) of verification should be true I have found that signature for AT,FR, IT and PL won't verify.
I have been taking examples of two doses from https://github.com/eu-digital-green-certificates/dgc-testdata
Do you think it might be something with data or do we need some additional tweaks to signature verification mechanism?

**Comment by gunnarif** [comment]
Hi @kansasdev  
there is a fix in the pull request that has not been accepted yet. 
I recommend you refer to https://github.com/gunnarif/hcert-dotnet-1 until the pr has been accepted

**Comment by kansasdev** [comment]
Thanks for quick answer, I have taken a look on your PR and now my test cases for verification are performed fine.
